# XGB Boost Book
### Various Functions

#### Data Extraction Function

In [2]:
import numpy as np
import pandas as pd
import zipfile
import urllib.request

In [11]:
url = 'https://github.com/mattharrison/datasets/raw/master/data/kaggle-survey-2018.zip'
fname = 'kaggle-survey-2018.zip'
member_name = 'multipleChoiceResponses.csv'

In [12]:
def extract_zip(src,dst,member_name):
    """Extract a memeber file from a zip file and read it into a panadas dataframe
    Parameter:
        src(str): URL of the target zip file
        dst (str): Local file path where the zip file will be written
        member_name(str): name of the memeber file inside the zip file to pull data from
    
    Returns: 
        a Panadas DataFrame containing the conentsd of the member_name file
    """

    url = src
    fname = dst
    fin = urllib.request.urlopen(url)
    data = fin.read()

    with open(dst, mode='wb') as fout:
        fout.write(data)
    with zipfile.ZipFile(dst) as z:
        kag = pd.read_csv(z.open(member_name))
        kag_questions = kag.iloc[0]
        raw = kag.iloc[1:]
        return raw

In [13]:
raw = extract_zip(url, fname, member_name)

C:\Users\cmurr\AppData\Local\Temp\ipykernel_7064\4032541412.py:20: DtypeWarning: Columns (0,2,8,10,21,23,24,25,26,27,28,42,44,54,56,64,81,83,85,87,105,107,109,121,123,125,148,150,157,172,174,192,194,210,218,219,221,223,246,247,249,262,264,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,302,304,306,325,326,329,341,368,371,384,385,389,390,391,393,394) have mixed types. Specify dtype option on import or set low_memory=False.
  kag = pd.read_csv(z.open(member_name))

In [14]:
raw.head()

,Time from Start to Finish (seconds),Q1,Q1_OTHER_TEXT,Q2,Q3,Q4,Q5,Q6,Q6_OTHER_TEXT,Q7,...,Q49_OTHER_TEXT,Q50_Part_1,Q50_Part_2,Q50_Part_3,Q50_Part_4,Q50_Part_5,Q50_Part_6,Q50_Part_7,Q50_Part_8,Q50_OTHER_TEXT
1,710,Female,-1,45-49,United States of America,Doctoral degree,Other,Consultant,-1,Other,...,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1
2,434,Male,-1,30-34,Indonesia,Bachelor’s degree,Engineering (non-computer focused),Other,0,Manufacturing/Fabrication,...,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1
3,718,Female,-1,30-34,United States of America,Master’s degree,"Computer science (software engineering, etc.)",Data Scientist,-1,I am a student,...,-1,NaN,Too time-consuming,NaN,NaN,NaN,NaN,NaN,NaN,-1
4,621,Male,-1,35-39,United States of America,Master’s degree,"Social sciences (anthropology, psychology, soc...",Not employed,-1,NaN,...,-1,NaN,NaN,Requires too much technical knowledge,NaN,Not enough incentives to share my work,NaN,NaN,NaN,-1
5,731,Male,-1,22-24,India,Master’s degree,Mathematics or statistics,Data Analyst,-1,I am a student,...,-1,NaN,Too time-consuming,NaN,NaN,Not enough incentives to share my work,NaN,NaN,NaN,-1

In [15]:
raw.shape

(23859, 395)

In [16]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23859 entries, 1 to 23859
Columns: 395 entries, Time from Start to Finish (seconds) to Q50_OTHER_TEXT
dtypes: object(395)
memory usage: 71.9+ MB

In [18]:
raw.describe().T

,count,unique,top,freq
Time from Start to Finish (seconds),23859,7641,101,31
Q1,23859,4,Male,19430
Q1_OTHER_TEXT,23859,69,-1,21738
Q2,23859,12,25-29,6159
Q3,23859,58,United States of America,4716
...,...,...,...,...
Q50_Part_5,3569,1,Not enough incentives to share my work,3569
Q50_Part_6,1059,1,I had never considered making my work easier f...,1059
Q50_Part_7,2500,1,None of these reasons apply to me,2500
Q50_Part_8,520,1,Other,520
Q50_OTHER_TEXT,23859,414,-1,21421